#!/usr/bin/env python3

import sys

import symbol_table

# Only allow a single input file
if len(sys.argv) == 2:
    input_file = sys.argv[1]
    output_file = input_file.split('.')[0] + '.hack'
else:
    sys.exit("Only 1 input file is allowed")


# TODO: put this in parser.py
def strip_whitespace_and_comments(input_file):
    """Strip whitespace and remove comments from each line in the input file"""
    stripped_lines = []
    with open(input_file, "r") as f:
        for line in f:
            stripped_line = line.strip()
            if stripped_line:
                if not stripped_line.startswith("//"):
                    if "//" in stripped_line:
                        stripped_lines.append(stripped_line.split("//")[0].strip())
                    else:
                        stripped_lines.append(stripped_line)
    return stripped_lines


stripped_lines = strip_whitespace_and_comments(input_file)
symbol_table = symbol_table.SymbolTable()
build_symbol_table = symbol_table.build_symbol_table(stripped_lines)
print(build_symbol_table)

